In [2]:
import numpy as np
import pandas as pd
import seaborn as sns

In [3]:
df = sns.load_dataset('iris')
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [4]:
#y=ax+c
#:rain #testing   supervised ML
#80:20
df['species'].value_counts()

setosa        50
versicolor    50
virginica     50
Name: species, dtype: int64

In [5]:
x=df.iloc[:,0:4].values # filter Independent variable
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
y=df.iloc[:,4].values  # filter dependent variable
y

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [7]:
#convert Y in numbers encoding

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
labelencoder_y= LabelEncoder()

In [10]:
y=labelencoder_y.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
from sklearn.model_selection import train_test_split 

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)
x_train

array([[4.8, 3.4, 1.9, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [6.7, 2.5, 5.8, 1.8],
       [6.9, 3.1, 5.1, 2.3],
       [7.9, 3.8, 6.4, 2. ],
       [5. , 3.4, 1.6, 0.4],
       [6.3, 2.8, 5.1, 1.5],
       [5. , 3.5, 1.6, 0.6],
       [6.2, 2.9, 4.3, 1.3],
       [6.1, 2.8, 4. , 1.3],
       [6.5, 3. , 5.2, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.8, 2.8, 4.8, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [5.8, 2.8, 5.1, 2.4],
       [4.6, 3.1, 1.5, 0.2],
       [6.4, 3.2, 5.3, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3.1, 4.7, 1.5],
       [5.4, 3.7, 1.5, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.5, 2.3, 1.3, 0.3],
       [7.4, 2.8, 6.1, 1.9],
       [5.1, 3.8, 1.6, 0.2],
       [6.2, 2.2, 4.5, 1.5],
       [5.4, 3.9, 1.7, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 4.4, 1.5, 0.4],
       [7.2, 3.6, 6.1, 2.5],
       [5.1, 3.7, 1.5, 0.4],
       [4.9, 3.6, 1.4, 0.1],
       [5.7, 2.6, 3.5, 1. ],
       [5.7, 2.8, 4.5, 1.3],
       [6.2, 3

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)
print(f'x_train',x_train)
print(f'x_test',x_test)
print(f'y_train',y_train)
print(f'y_test',y_test)

x_train [[5.6 3.  4.5 1.5]
 [5.7 2.6 3.5 1. ]
 [6.3 3.3 6.  2.5]
 [5.4 3.4 1.7 0.2]
 [4.8 3.  1.4 0.1]
 [5.  2.  3.5 1. ]
 [5.1 3.8 1.5 0.3]
 [5.1 3.8 1.6 0.2]
 [6.4 2.8 5.6 2.2]
 [6.2 3.4 5.4 2.3]
 [5.1 3.5 1.4 0.3]
 [5.6 3.  4.1 1.3]
 [7.  3.2 4.7 1.4]
 [5.5 2.6 4.4 1.2]
 [6.7 3.3 5.7 2.1]
 [6.4 2.7 5.3 1.9]
 [5.2 4.1 1.5 0.1]
 [6.3 2.9 5.6 1.8]
 [5.4 3.7 1.5 0.2]
 [5.9 3.  5.1 1.8]
 [6.3 2.8 5.1 1.5]
 [5.8 2.7 5.1 1.9]
 [5.2 3.5 1.5 0.2]
 [5.5 3.5 1.3 0.2]
 [6.5 3.  5.8 2.2]
 [4.4 3.  1.3 0.2]
 [5.  3.4 1.6 0.4]
 [6.7 3.1 4.4 1.4]
 [4.9 2.4 3.3 1. ]
 [5.6 2.5 3.9 1.1]
 [5.9 3.2 4.8 1.8]
 [6.6 2.9 4.6 1.3]
 [5.  3.6 1.4 0.2]
 [6.9 3.2 5.7 2.3]
 [5.8 2.7 5.1 1.9]
 [6.7 3.  5.2 2.3]
 [5.7 3.8 1.7 0.3]
 [7.4 2.8 6.1 1.9]
 [6.1 2.8 4.7 1.2]
 [5.8 2.7 4.1 1. ]
 [4.9 3.  1.4 0.2]
 [6.  2.7 5.1 1.6]
 [4.9 3.6 1.4 0.1]
 [7.9 3.8 6.4 2. ]
 [6.5 3.  5.5 1.8]
 [5.1 3.3 1.7 0.5]
 [5.7 2.5 5.  2. ]
 [6.7 3.1 5.6 2.4]
 [6.9 3.1 4.9 1.5]
 [4.6 3.2 1.4 0.2]
 [4.9 2.5 4.5 1.7]
 [6.3 2.3 4.4 1.3]
 [4.

In [14]:
x_train.size

420

In [15]:
x_test.size

180

In [16]:
y_train.size

105

In [17]:
y_test.size

45

In [18]:
from sklearn.linear_model import LogisticRegression

In [19]:
logmodel=LogisticRegression()
logmodel.fit(x_train,y_train)

C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [20]:
y_pred= logmodel.predict(x_test)

In [21]:
y_pred
np.sort(y_pred)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2])

In [22]:
y_test
np.sort(y_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2])

In [23]:
from sklearn.metrics import confusion_matrix

In [24]:
confusion_matrix(y_test,y_pred)

array([[17,  0,  0],
       [ 0, 13,  1],
       [ 0,  1, 13]], dtype=int64)

In [25]:
(28/30)*100

93.33333333333333

In [26]:
logmodel.score(x_test,y_test)

0.9555555555555556

In [27]:
from sklearn.neighbors import KNeighborsClassifier  


In [28]:
classifier_knn= KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2) # distance name

In [29]:
classifier_knn.fit(x_train,y_train) # model training 70:30

KNeighborsClassifier()

In [31]:
y_pred_knn=classifier_knn.predict(x_test)
y_pred_knn

array([0, 0, 2, 1, 2, 0, 2, 0, 0, 0, 1, 1, 2, 0, 2, 2, 1, 0, 0, 2, 2, 1,
       0, 1, 2, 0, 0, 2, 1, 0, 2, 1, 2, 0, 0, 2, 1, 2, 1, 2, 1, 0, 0, 1,
       1])

In [32]:
from sklearn.metrics import confusion_matrix

In [33]:
confusion_matrix(y_test,y_pred_knn)

array([[17,  0,  0],
       [ 0, 13,  1],
       [ 0,  0, 14]], dtype=int64)

In [34]:

classifier_knn.score(x_test,y_test)

0.9777777777777777

In [35]:
# NaiveBias Model
from sklearn.naive_bayes import GaussianNB

In [36]:
classifier_nb= GaussianNB()

In [37]:
classifier_nb.fit(x_train,y_train)

GaussianNB()

In [38]:
y_pred= classifier_nb.predict(x_test)

In [39]:
y_pred

array([0, 0, 2, 1, 2, 0, 2, 0, 0, 0, 1, 1, 2, 0, 1, 2, 1, 0, 0, 2, 2, 1,
       0, 1, 2, 0, 0, 2, 1, 0, 1, 1, 2, 0, 0, 2, 1, 2, 1, 2, 1, 0, 0, 1,
       1])

In [40]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred_knn,y_test)

0.9777777777777777

In [43]:
confusion_matrix(y_test,y_pred)

array([[17,  0,  0],
       [ 0, 13,  1],
       [ 0,  2, 12]], dtype=int64)

In [44]:
classifier_nb.score(x_test,y_test)

0.9333333333333333